/**
* На промоигле
* Задача для Alfa Battle от X5 Retail Group
*
* OpenAPI spec version: 1.0.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package com.alfabattle.contest.promo


/**
 * Результат расчета корзины
 * @param discount Полная сумма скидки
 * @param positions Результат расчета цен по позициям
 * @param total Полная сумма чека с применением скидок
 */
data class FinalPriceReceipt (
    /* Полная сумма скидки */
    val discount: java.math.BigDecimal? = null,
    /* Результат расчета цен по позициям */
    val positions: kotlin.Array<FinalPricePosition>? = null,
    /* Полная сумма чека с применением скидок */
    val total: java.math.BigDecimal? = null
) {

}

