/**
* На промоигле
* Задача для Alfa Battle от X5 Retail Group
*
* OpenAPI spec version: 1.0.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package com.alfabattle.contest.promo

import com.alfabattle.contest.promo.ItemCountRule

/**
 * Матрица промо-механик
 * @param itemCountRules Список правил при покупке определенного количества единиц конкретного товара
 * @param itemGroupRules Список правил при покупке связанных товаров
 * @param loyaltyCardRules Список правил скидки при предъявлении пенсионного удостоверения или социальной карты
 */
data class PromoMatrix (
    /* Список правил при покупке определенного количества единиц конкретного товара */
    val itemCountRules: kotlin.Array<ItemCountRule>? = null,
    /* Список правил при покупке связанных товаров */
    val itemGroupRules: kotlin.Array<ItemGroupRule>? = null,
    /* Список правил скидки при предъявлении пенсионного удостоверения или социальной карты */
    val loyaltyCardRules: kotlin.Array<LoyaltyCardRule>? = null
) {

}

