/**
* Сервис проверки статуса банкоматов
* Сервис, возвращающий информацию о банкоматах Альфа-Банка
*
* OpenAPI spec version: 1.0.0
* Contact: apisupport@alfabank.ru
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package com.alfabattle.contest.alfa


/**
 * Информация по доступности функций АТМ
 * @param availableNow Работоспособность АТМ по данным поставщика информации на момент выполнения запроса
 * @param deviceId Номер Terminal-ID, присвоенный АТМ в процессинге Банка и передаваемый в информационном обмене между эквайрером, платежной системой и эмитентом.  Значение соответствует ISO-8583 полю 41 (Card Acceptor Terminal Identification)
 * @param recordUpdated Дата/время получения последней информации из master-системы
 */
data class ATMStatus (
    /* Работоспособность АТМ по данным поставщика информации на момент выполнения запроса */
    val availableNow: AvailableNow? = null,
    /* Номер Terminal-ID, присвоенный АТМ в процессинге Банка и передаваемый в информационном обмене между эквайрером, платежной системой и эмитентом.  Значение соответствует ISO-8583 полю 41 (Card Acceptor Terminal Identification) */
    val deviceId: kotlin.Int? = null,
    /* Дата/время получения последней информации из master-системы */
    val recordUpdated: java.time.LocalDateTime? = null
) {

}

