/**
* Сервис проверки статуса банкоматов
* Сервис, возвращающий информацию о банкоматах Альфа-Банка
*
* OpenAPI spec version: 1.0.0
* Contact: apisupport@alfabank.ru
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package com.alfabattle.contest.alfa


/**
 * 
 * @param latitude Широта
 * @param longitude Долгота
 */
data class Coordinates (
    /* Широта */
    val latitude: kotlin.String? = null,
    /* Долгота */
    val longitude: kotlin.String? = null
) {

}

