/**
* Сервис проверки статуса банкоматов
* Сервис, возвращающий информацию о банкоматах Альфа-Банка
*
* OpenAPI spec version: 1.0.0
* Contact: apisupport@alfabank.ru
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package com.alfabattle.contest.alfa


/**
 * 
 * @param code Код ошибки
 * @param message Сообщение об ошибке
 */
data class Error (
    /* Код ошибки */
    val code: kotlin.Int? = null,
    /* Сообщение об ошибке */
    val message: kotlin.String? = null
) {

}

