/**
* Сервис проверки статуса банкоматов
* Сервис, возвращающий информацию о банкоматах Альфа-Банка
*
* OpenAPI spec version: 1.0.0
* Contact: apisupport@alfabank.ru
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package com.alfabattle.contest.alfa



/**
 * 
 * @param &#x60;data&#x60; Данные
 * @param error Информация об ошибке в слчуае если success = false
 * @param success Успешность выполнения запроса
 * @param total Общее количество элементов в списке, если в атрибуте data передается список
 */
data class JSONResponseBankATMDetails (
    /* Данные */
    val `data`: BankATMDetails? = null,
    /* Информация об ошибке в слчуае если success = false */
    val error: Error? = null,
    /* Успешность выполнения запроса */
    val success: kotlin.Boolean? = null,
    /* Общее количество элементов в списке, если в атрибуте data передается список */
    val total: kotlin.Int? = null
) {

}

