/**
 * Сервис проверки статуса банкоматов
 * Сервис, возвращающий информацию о банкоматах Альфа-Банка
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apisupport@alfabank.ru
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package com.alfabattle.contest.alfa


/**
 *
 * @param city
 * @param location
 * @param mode
 */
data class PostAddress(
        val city: kotlin.String? = null,
        val location: kotlin.String? = null,
        val mode: PostAddress.Mode? = null
) {

    /**
     *
     * Values: fIAS,kLADR,otherDictionary,handMade
     */
    enum class Mode(val value: kotlin.String) {

        fIAS("FIAS"),

        kLADR("KLADR"),

        otherDictionary("OtherDictionary"),

        handMade("HandMade");

    }

}

