/**
* Сервис проверки статуса банкоматов
* Сервис, возвращающий информацию о банкоматах Альфа-Банка
*
* OpenAPI spec version: 1.0.0
* Contact: apisupport@alfabank.ru
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package com.alfabattle.contest.alfa


/**
 * 
 * @param email Адрес электронной почты
 * @param other Иные контакты поддержки
 * @param phone Телефон
 */
data class SupportInfo (
    /* Адрес электронной почты */
    val email: kotlin.String? = null,
    /* Иные контакты поддержки */
    val other: kotlin.String? = null,
    /* Телефон */
    val phone: kotlin.String? = null
) {

}

